collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "_author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "_post"
  - scope:
      path: "singles"
      type: "pages"
    values:
      layout: "base"
  - scope:
      path: ""
    values:
      layout: "home"


